apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: cilium
    repo: https://helm.cilium.io
    version: 1.16.6
    releaseName: cilium
    namespace: kube-system
    valuesFile: cilium-proxyless.values.yaml
    includeCRDs: true
commonAnnotations:
  platform.hmg.dev/built-by: kustomize
  platform.hmg.dev/component: cilium
