envoy:
  service:
    type: NodePort
    externalTrafficPolicy: Cluster
defaultBackend:
  enabled: true
configInline:
  accesslog-format: envoy
  disablePermitInsecure: false
  gateway:
    controllerName: projectcontour.io/gateway-controller