gateway:
  http:
    nodePort: 30080
  tls:
    nodePort: 30443
admin:
  credentials:
    admin: weaknesspays
    viewer: foobar
    # Use secretName here in the future
etcd:
  replicaCount: 1
ingress-controller:
  enabled: true
  config:
    apisix:
      serviceNamespace: apisix
      adminKey: weaknesspays