apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
helmCharts:
- name: apisix
  repo: https://charts.apiseven.com
  version: 1.4.0
  releaseName: apisix
  namespace: apisix
  valuesFile: apisix.values.yaml
  includeCRDs: true
commonAnnotations:
  platform.hmg.dev/built-by: kustomize
  platform.hmg.dev/component: apisix