controller:
  config:
    allow-snippet-annotations: "true"
    annotations-risk-level: Critical
    disable-ipv6-dns: "true"
    disable-ipv6: "true"
    force-ssl-redirect: "true"
    large-client-header-buffers: "8 16k"
    proxy-buffer-size: "128k"
    ssl-reject-handshake: "true"
    use-gzip: "true"
    enable-brotli: "true"
    generate-request-id: "true"
    custom-http-errors: "401,403,404,500"
  replicaCount: 1
  metrics:
    enabled: true
  podAnnotations:
    "prometheus.io/scrape": "true"
    "prometheus.io/port": "10254"
  service:
    externalTrafficPolicy: Local
defaultBackend:
  enabled: true
  image:
    repository: local/minidefaultbackend
    tag: c19036e6c35224a904c624ab58a1f28efc6bdfaa27355dcaa8093c8ae362dcd1
  nodeSelector:
    "kubernetes.io/os": linux
