controller:
  config:
    allow-snippet-annotations: "true"
    annotations-risk-level: Critical
    force-ssl-redirect: "true"
    disable-ipv6: "true"
    disable-ipv6-dns: "true"
    http-snippet: |
      # anticipate developers being developers
      nginx_http_large_client_header_buffers 4 8k;
  replicaCount: 2
  metrics:
    enabled: true
  podAnnotations:
    "prometheus.io/scrape": "true"
    "prometheus.io/port": "10254"
  service:
    externalTrafficPolicy: Local
defaultBackend:
  nodeSelector:
    "kubernetes.io/os": linux
