apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: minidefaultbackend
  name: minidefaultbackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minidefaultbackend
  template:
    metadata:
      labels:
        app: minidefaultbackend
    spec:
      containers:
        - image: local/minidefaultbackend:d2c15c994ea12b5bcf775fffab855000cd60317b70f0733fc5715412c2b22109
          name: minidefaultbackend
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              cpu: 100m
